## Author: Tito Valentin
## Name of Program: dirPathPerms Gitleaks Configuration
## Date Created: 2026-07-13
## Description: Extends the default Gitleaks rules for repository history scans.
title = "dirPathPerms gitleaks configuration"

[extend]
useDefault = true
